### ISSUE TITLE
Diving on the same frame as spinning makes the spin sound for as long as you keep diving

### ISSUE THREAD

**Issue by Vexxter9** [GTcreyon/SM63Redux#101]
**Describe the bug**
When you spin and dive on the same frame, the spinning sound keeps playing for as long as you are still in the diving animation.

**To Reproduce**
Press X and down arrow at the same time

**Expected behavior**
The spin sound should stop

**Screenshots**
That wouldn't even help

**System Information**
 - OS/Browser: Windows 10
 - Game version: v0.1.6.RC1
 - Other specs: Has motherboard, CPU and GPU 👍

**Additional context**
This also happens with ground pounding, although that one stops when touching the ground so it's less noticeable

**Comment by Kuma-Boo** [comment]
After some testing, there seems to be an underlying issue with how the spin sfx is handled, as I've managed to recreate this issue with the following states:

- jump + spin
- crouch + spin
- interact with sign + spin

I'll continue to look into this and see if I can make a fix.
