### ISSUE TITLE
Using FLUDD and a sign simultaneously will produce a buzzing noise

### ISSUE THREAD

**Issue by AidenBeresford** [GTcreyon/SM63Redux#115]
**Describe the bug**
FLUUD Groundpounding and interacting with a sign creates a loud buzzing noise, similar to that of a chainsaw, while your FLUUD shoots out tons of water.

**To Reproduce**
Press Z and Space simultaneously while in front of a sign.

**Expected behavior**
Ordinarily, you would enter the sign's text box, and your FLUUD would stop spraying out water. There shouldn't be a buzzing noise either.

**Screenshots**
![image](https://user-images.githubusercontent.com/18747155/226143375-d365458b-61f5-40cf-84b7-77b1932b384e.png)

**System Information**
 - OS/Browser: Ubuntu Linux
 - Game version: 0.20.0
 - Other specs: Not applicable

**Comment by Koopa1018** [comment]
Successfully reproduced. t1r4, where the screenshot shows, is the easiest place to observe the effects.

Power bar continues animating during bug, but bar level and water in tank do not go down.

May have similar root cause to #59.
