### ISSUE TITLE
Rewrite menu system to build menus from a written pattern

### ISSUE THREAD

**Issue by GTcreyon** [GTcreyon/SM63Redux#13]
**Describe the feature you'd like**
List menus such as the options menu are currently built in Godot's scene editor. This works, but it's clunky and hard to work with. It's also not very dynamic, and it makes the underlying code messy. I believe it would scale better if we created a number of standardised control prefabs (which we mostly do already, in the form of tickboxes), and load them into a menu by interpreting some kind of written data, such as a JSON string or other resource that can easily be edited.

**Do you intend to contribute this yourself? If so, how do you plan on doing it?**
- I might contribute myself, but not for a while if so.
- I don't think a separate file would be necessary to store the pattern, since it could be stored in a multiline exported string variable.
- Having some kind of container control that generates a menu from a given input pattern could be useful. It might even be nice to make it possible to then include another sub-menu (particularly for the options menu, where the controls menu is contained within it)
- Controls should be able to be hidden or shown based on some boolean condition. Probably unnecessary to have this dynamically evaluated, just have it pull from a named variable. Perhaps a dictionary or something. I'm not sure if accessing an arbitrarily named variable is secure.

**Comment by GTcreyon** [comment]
This would probably close #2, #3, and #8.

**Comment by sbritorodr** [comment]
What about doing a _menupopup_ explained in this tutorial?: https://www.davidepesce.com/2020/02/11/godot-tutorial-16-pause-menu-restart-quit-game/

**Comment by GTcreyon** [comment]
Looking back, I think this is a bad idea. There's nothing this can do that can't be achieved better with a solid understanding of Godot's `Control` nodes.
