### ISSUE TITLE
Spinning into koopa produces error and two shells

### ISSUE THREAD

**Issue by nyanpasu64** [GTcreyon/SM63Redux#130]
**Describe the bug**
When spinning into a wingless koopa, a queue_free warning is printed and two shells are spawned.

**To Reproduce**
- Enter stage 3 of the demo.
- Jump on the parakoopa, then spin into the koopa from the ground on the side.

Results:

- First `_on_HurtboxStrike_body_entered` calls `_hurt_struck(body = player) -> into_shell`.
- Then (on the same frame I think?) `_physics_step()` calls `_hurtbox_check()` which also calls `_hurt_struck`.

`into_shell` is called twice on the same frame (I think), and each call spawns a separate shell and calls `queue_free()` on the koopa. I'm not sure if the koopa is freed before the next `_process` or `_physics_process`.

Sometimes the two shells are spawned at slightly different positions, other times on top of each other (producing a very loud shell sound, and every subsequent kick is loud too because two copies of the shell kick sound play on top of each other).

Because `_hurt_struck` is called twice, it calls `ResidualSFX.new_from_existing` twice, resulting in error:

```
E 0:39:39.579   connect: Signal 'finished' is already connected to given method 'queue_free' in that object.
  <C++ Error>   Method failed. Returning: ERR_INVALID_PARAMETER
  <C++ Source>  core/object.cpp:1480 @ connect()
  <Stack Trace> residual_sfx.gd:42 @ new_from_existing()
                koopa.gd:60 @ _hurt_struck()
                entity_enemy.gd:102 @ _hurtbox_check()
                entity_enemy.gd:95 @ _physics_step()
                entity_enemy_walk.gd:56 @ _physics_step()
                entity.gd:59 @ _physics_process()
```

**Expected behavior**
One koopa shell spawns. I'm not sure which call to `_hurt_struck` should be removed, or if we should make koopa's `_hurt_struck` [idempotent](https://en.wikipedia.org/wiki/Idempotence) so calling it twice does the same thing as calling once (for example we could set a "will be destroyed" flag, and make the method do nothing if we call it again and the flag is already set).

**Screenshots**
![Godot_v3 5 2-stable_win64_yKfQHZMQZB](https://user-images.githubusercontent.com/913957/229302806-132d1110-797b-4729-b77b-b84234002366.png)

**System Information**
 - OS/Browser: Windows 10
 - Game version: master 93835e18640ed009ae033c12dac0cc8c453b347b + `$Damage.set_deferred("monitoring", false)`
 - Other specs:

**Additional context**

**Comment by AidenBeresford** [comment]
Having trouble replicating this on the master branch, so I'm assuming this is related to the `$Damage.set_deferred("monitoring", false)` edit you made. Can you be more specific with what exactly you changed?

**Comment by nyanpasu64** [comment]
Replicated on master 93835e18640ed009ae033c12dac0cc8c453b347b:

https://www.youtube.com/watch?v=bgbNio2a-pU

Sorry, the SD recording only uploads to YouTube at 30fps.
