### ISSUE TITLE
Going backwards while `stop crouching` animation plays

### ISSUE THREAD

**Issue by WSDguy2014** [GTcreyon/SM63Redux#180]
**Describe the bug**
Player can go backwards while doing 'stop crouching' animation.

**To Reproduce**
- Stand still.
- Hold down arrow button to crouch.
- Hold either left or right arrow key that you want to go opposite from what your direction is currently facing (notice that Mario is not facing to the other direction while crouching without slight movement).
- Now alternate releasing and pressing down key as many times as you want while going backwards.

**Expected behavior**
Player should facing other way during this animation, instead of waiting for the animation to end and then facing the other direction.

**Video**

https://github.com/GTcreyon/SM63Redux/assets/13905392/c427dad0-b693-41bb-b63c-8df7f941b725

**System Information**
 - OS/Browser: Windows 10 / Avast Secure Browser (version 113.0.21244.127 (Official Build) (64-bit))
 - Game version: v0.1.6.alpha

**Additional context**
Imagine having custom 'don't look away' courses/levels that utilizes this, and backflip movement doesn't exist and is not an option?

**Comment by GTcreyon** [comment]
How would we go about fixing this?

**Comment by WSDguy2014** [comment]
It's up to your preference if you want to fix this or not.
My opinion is that this bug should be fixed, otherwise as what I said earlier in the additional context that this would lead to some interesting unusual movement tech like this that's been used in future custom courses/levels and newcomer/casual players would not understand how to perform this movement.

**Maybe an alternative expected behavior idea for the fix would be:** player would still not move during this animation, waiting for the animation to end and then facing & moving the other direction.
