### ISSUE TITLE
Question: how do i compile the latest fully unlocked build from the source code?

### ISSUE THREAD

**Issue by soupnuts6061** [GTcreyon/SM63Redux#185]
just wondering

**Comment by Koopa1018** [comment]
This stumped me too for a while. Here's what I've figured out; it should work regardless of platform, but I've only tested on Windows.

# The first time...
## Step 1: Open the project in Godot
Idk if you have Godot yet; if you don't, it's free, and it's only a couple hundred megabytes. 
Use version 3.5, NOT version 4.0--the project hasn't been updated to the 4.x series yet, and I've seen it break horribly before.

Here's a link to the right download: https://godotengine.org/download/3.x/windows/

## Step 2: Open the export window
That's done using Project > Export, right here:
![image](https://github.com/GTcreyon/SM63Redux/assets/29995463/e5b3a86c-fc6b-410d-afba-2982333ad5ae)

## Step 3: Add build targets
This is the part that stumped me. You're looking for an "Add..." button at the top of the export window--but it DOESN'T LOOK LIKE A BUTTON. It looks like a label.
![image](https://github.com/GTcreyon/SM63Redux/assets/29995463/7f98242d-512a-423e-a419-4c9a76574070)

Add whichever one matches your platform, plus whichever ones else you want.

## Step 4: Configure build targets
Not sure what OS you're on, but if you just want it up and running, the default settings are probably fine.

## Step 5: Click "Export Project" and save the file
...or "Export All" if you have multiple build targets.

#Every time after....
Build targets stay added and configured after you're done exporting, so you can pretty much just skip steps 3 and 4 from there on out.

**Comment by soupnuts6061** [comment]
you goofy i said fully unlocked not tiny demo!

**Comment by GTcreyon** [comment]
We haven't made any more than that yet. Koopa's answer gives you the most up-to-date version.

**Comment by soupnuts6061** [comment]
ah, alright
