### ISSUE TITLE
Ground-pound fludd bug

### ISSUE THREAD

**Issue by sbritorodr** [GTcreyon/SM63Redux#19]
**Describe the bug**
After a groundpound, if you activate fludd you won't leave the ground, reseting the cooldown fludd and making a sound glitch as well.

**To Reproduce**
Jump. Press and hold Z+C

**Expected behavior**
Mario should end the ground-pound animation, make a small jump and activate fludd correctly.

**Screenshots**
Not necessary

**System Information**
 - OS/Browser: Windows, MacOS, but I think is not relevant here
 - Game version: v 0.2.0
 - Other specs:

**Comment by GTcreyon** [comment]
This is handled by #11. Not sure if @nyanpasu64 is likely to finish that draft, but if needed we could assign someone to pick it up.

**Comment by sbritorodr** [comment]
Okay, I'll leave this open until #11 is finally merged
