### ISSUE TITLE
Pause menu remains interactable while unpaused

### ISSUE THREAD

**Issue by GTcreyon** [GTcreyon/SM63Redux#2]
**Describe the bug**
While the game is unpaused, certain elements of the pause menu can still be interacted with via the mouse.

**To Reproduce**
- Pause the game
- Go to Options
- Unpause the game
- Click the mouse where the language options used to be

**Expected behavior**
The pause menu should not be interactable while the game is unpaused.

**System Information**
 - OS/Browser: All versions
 - Game version: 0.2.0.alpha

**Comment by Koopa1018** [comment]
Ah hm, apparently the first commit that mentions an issue closes it...good to know
