### ISSUE TITLE
Cheats

### ISSUE THREAD

**Issue by ChaseyBOIDude** [GTcreyon/SM63Redux#20]
In the original, @runouw  added cheats, I tested the feature by typing "cheat" and it brought me back to the start of the level. 

The cheats in the original were to unlock everything (example: You can unlock the basement door without defeating Bowser) and to toggle Shine Sprites on the Star Map, It would be a cool secret to include into the game, just don't tell anyone ;)

**Comment by GTcreyon** [comment]
If you press `/`, it will open up a command line that you can enter cheats into. Try `fludd all`, `health INF` and `cherry` in particular.

We won't add the original cheat menu, but we might add the Unlock Everything and Toggle Shine cheats do the command console at some point.

Hope that helps!
