### ISSUE TITLE
Unlimited FLUDD Gauge When Ducking

### ISSUE THREAD

**Issue by ChaseyBOIDude** [GTcreyon/SM63Redux#21]
When using the FLUDD if you duck while pressing "c" the Fuel Gauge will not go down, while in the air it does go down.
[Screen recording 2022-11-23 6.38.23 PM.webm](https://user-images.githubusercontent.com/118941203/203664296-09698c07-21ab-434b-8778-6081b2fc5ac2.webm)

**Comment by GTcreyon** [comment]
This is intended behaviour. The Power meter is only there to stop you flying endlessly. It works the same way in the original.
