### ISSUE TITLE
Sequel?

### ISSUE THREAD

**Issue by ChaseyBOIDude** [GTcreyon/SM63Redux#22]
**Describe the feature you'd like**
Not right now but after "SM63 Redux" is finished I want to make the sequel to it, called "SM63 : Toad's Revenge"

**Do you intend to contribute this yourself? If so, how do you plan on doing it?**
A bit, I have **TONS** of ideas for the sequel, but I am not a expert in coding, so I need some help.

![Screenshot 2022-11-23 8 48 41 PM (1)](https://user-images.githubusercontent.com/118941203/203679545-11669bab-0f66-4e2c-a94b-6bf3599e2bf8.png)

**Additional context**
just so you know, this will happen around 2 years after "SM63 Redux" is finished, maybe it won't happen, this is just a concept, ok.

**Comment by GTcreyon** [comment]
Check out Super Mario 127 for a sequel.

**Comment by GTcreyon** [comment]
2^6 - 1 = 63
2^7 - 1 = 127
https://youtu.be/G3WcqhSSlHw

Locking this now.
