### ISSUE TITLE
FLUDD spray cuts off in resized windows

### ISSUE THREAD

**Issue by Koopa1018** [GTcreyon/SM63Redux#229]
**Describe the bug**
In the 4.1 branch, resizing the window exposes the edges of the FLUDD spray viewport. When the particle stream hits the edge, it cuts off; if it starts below the edge, nothing shows in the first place.

**To Reproduce**
1. Size up the window--but not enough that the pixels resize.
2. Use FLUDD in the middle of the screen.
3. Use FLUDD in the edge of the screen.

**Expected behavior**
FLUDD particles' cutoff point is never visible within the screen bounds.

**Screenshots**
![image](https://github.com/GTcreyon/SM63Redux/assets/29995463/273b301d-f5a1-408a-a939-4b5bbfd100a0)

**System Information**
 - OS/Browser: Windows 10
 - Game version: 4.1 branch
 - Other specs: N/A

**Additional context**
May be caused by the window-size zoom bug #230. The best fix for this may be to fix that. Evaluate whether this can be reproduced with that problem fixed.

**Comment by GTcreyon** [comment]
Still reproducible. I suspect it may be due to the inverted zooming in 4.1?

**Comment by GTcreyon** [comment]
I was wrong. Found something that seems to work - PR incoming.
