### ISSUE TITLE
Resizing window adjusts zoom too late

### ISSUE THREAD

**Issue by Koopa1018** [GTcreyon/SM63Redux#230]
**Describe the bug**
Since the 4.1 update, the camera zoom has changed with window size much later than it should. This allows players, by resizing the window, to see much more of the level than they should.

63R's default screen resolution is 640x360.
In release v0.1.6.alpha, making the window ~30 pixels taller would double the camera zoom, making pixels twice as big.
In the 4.1 branch, the window's height has to practically double before the camera zoom will double.
The horizontal axis suffers the same problem.

**To Reproduce**
1. Enter T1.
2. Resize the window on either axis.

**Expected behavior**
The screen zooms in as early as in the released demos, early enough that unreasonably large views of the level cannot happen.

**Screenshots**
![image](https://github.com/GTcreyon/SM63Redux/assets/29995463/8af694d0-8542-46a8-8047-9fa3dbbfd111)

**System Information**
 - OS/Browser: Windows 10
 - Game version: 4.1 branch
 - Other specs:

**Additional context**
Unclear whether #229 is caused or just made worse by this problem.

**Comment by sbritorodr** [comment]
Tried to reproduce this bug but seems to work fine on me. Should be solved then?

**Comment by Koopa1018** [comment]
Huh. What in the world was wrong with my copy of the repo?
