### ISSUE TITLE
Pause menu buttons' stars appear wrong

### ISSUE THREAD

**Issue by Koopa1018** [GTcreyon/SM63Redux#231]
**Describe the bug**
The buttons at the bottom of the pause menu have little scrolling star patterns on them. Since the 4.1 update, these stars have used the wrong visual behavior.

When things work as intended, the stars are meant to be stationary and somewhat faded. When the buttons are moused over, the stars begin scrolling, and they stop when the mouse leaves the button; when the buttons are pressed down, the stars become darkened with the button, and scroll regardless of where the mouse is.

Since the 4.1 update, the stars have always appeared as though their buttons are pressed, showing their darkened appearance and constantly scrolling.

**To Reproduce**
Visit the pause menu in the 4.1 branch.

**Expected behavior**
The stars respond to the mouse and the button's state as described above.

**Screenshots**
Top: release v0.1.6.alpha. Bottom: 4.1 branch. Motion not pictured.
![image](https://github.com/GTcreyon/SM63Redux/assets/29995463/1e6c4146-adc5-4b1a-8241-295877a7ee0c)

**System Information**
 - OS/Browser: Windows 10
 - Game version: 4.1 branch
 - Other specs: N/A

**Additional context**
N/A

**Comment by Koopa1018** [comment]
This seems to have somehow fixed itself...can anyone else repro?

**Comment by Kuma-Boo** [comment]
Can't seem to reproduce this.

**Comment by Koopa1018** [comment]
Seems to still happen in the branch `fix-incorrect-flud-size`, which predates #215. I guess one of us must've fixed this since then and I didn't notice?

**Comment by Koopa1018** [comment]
Huh! Looks like I myself did 😅 🤦
