### ISSUE TITLE
Water meter bubbles don't size up with window

### ISSUE THREAD

**Issue by Koopa1018** [GTcreyon/SM63Redux#237]
**Describe the bug**
When the window is sized up, the bubbles in FLUDD's water meter don't zoom with it. The result is a tank full of very tiny bubbles.

**To Reproduce**
In no particular order:
- Get FLUDD.
- Resize the window so that pixels become bigger.

**Expected behavior**
FLUDD's bubbles size up with the rest of the game.

**Screenshots**
Courtesy of Creyon's Discord report:
![image](https://github.com/GTcreyon/SM63Redux/assets/29995463/7af08c30-329a-476d-82e8-d8551d04c905)

**System Information**
 - OS/Browser: Repro'd on Windows 10, Godot editor
 - Game version: 4.1 branch
 - Other specs:

**Additional context**
N/A

**Comment by GTcreyon** [comment]
Closing.
