### ISSUE TITLE
Cherry clones do not spray water with FLUDD

### ISSUE THREAD

**Issue by ChaseyBOIDude** [GTcreyon/SM63Redux#24]
**Describe the bug**
Mario's Clone Spray's Water while Mario Dosen't.

**To Reproduce**
Press "/" and type in "cherry", then get the FLUDD and press "c".

**Expected behavior**
Both Mario and the Clone are going to spray water.
[Screen recording 2022-11-24 10.08.48 AM.webm](https://user-images.githubusercontent.com/118941203/203817509-b61f4956-eafc-4d14-9226-c9c38191b100.webm)

**System Information**
 - OS/Browser: Chrome
 - Game version: 0.1.5
 - Other specs:

**Additional context**
None

**Comment by GTcreyon** [comment]
> Would be closed by #16.

It was not, actually. This issue is more complex.

**Comment by Koopa1018** [comment]
Working on `bubbles.gd` to try and solve the problem.

Question: why does `hud` call `refresh()` on the bubbles in its process function, rather than `bubbles` doing that itself?

**Comment by GTcreyon** [comment]
> Working on `bubbles.gd` to try and solve the problem.
> 
> Question: why does `hud` call `refresh()` on the bubbles in its process function, rather than `bubbles` doing that itself?

I don't think there was a reason for it. Ask @jaschutte.
