### ISSUE TITLE
Water meter bubbles don't follow meter when resizing

### ISSUE THREAD

**Issue by Koopa1018** [GTcreyon/SM63Redux#246]
**Describe the bug**
Resizing the window makes the bubbles in the water meter appear to drift off, as though the source of the bubbles was being moved relative to them. With extreme changes, e.g. entering fullscreen, it appears as though the tank was suddenly emptied of bubbles.

**To Reproduce**
1. Get FLUDD.
2. Drag the right side of the screen to resize the window, at various speeds. Watch the bubbles in the water meter.
3. Enter and exit fullscreen repeatedly. Watch the bubbles reset each time.

**Expected behavior**
The bubbles move with the water meter when resizing.

**Screenshots**
![image](https://github.com/GTcreyon/SM63Redux/assets/29995463/1fe89f97-5546-4eec-a190-a35f1b6a9ca8)
that ain't right

**System Information**
 - OS/Browser: Windows 10, Godot editor
 - Game version: 4.1 branch
 - Other specs:

**Additional context**
May be related to #237,

**Comment by GTcreyon** [comment]
You say "as though the source of the bubbles was being moved relative to them" - I think this is literally the cause of the issue. We're moving the particle emitter since it's part of the scene tree, but we're not moving the particles because they're drawn arbitrarily by the GPU, or something.
