### ISSUE TITLE
New Sprite For Mario

### ISSUE THREAD

**Issue by ChaseyBOIDude** [GTcreyon/SM63Redux#25]
**Describe the feature you'd like**
To add this Sprite for Mario
![Screenshot 2022-11-24 10 26 52 AM](https://user-images.githubusercontent.com/118941203/203821625-1f3a1f1a-3647-4cc7-9ff3-c8f7a2d517cc.png)

**Do you intend to contribute this yourself? If so, how do you plan on doing it?**
No.

**Additional context**
There is a other sprite in the game that I call "Suprised Mario" I just can't find it.

**Comment by GTcreyon** [comment]
Mario's sprites will be added incrementally, when they're needed. This is therefore a duplicate issue.
