### ISSUE TITLE
Paratroopas make version control noise

### ISSUE THREAD

**Issue by Koopa1018** [GTcreyon/SM63Redux#255]
**Describe the bug**
Since the 4.1 update, Paratroopas' per-scene materials generate a new UID every time a level is opened containing them. These UID changes show up in version control, but are also completely useless and distract from actually-important changes being made.

**To Reproduce**
1. In the Godot editor, open any level with Paratroopas in it.
2. Save the level, without even making changes.
5. View the level in your Git client of choice.

**Expected behavior**
Level files only appear in version control when intentional changes were made.

**Screenshots**
![image](https://github.com/GTcreyon/SM63Redux/assets/29995463/8ffc242d-96a5-4efd-8fe4-8eb3fd60106b)

**System Information**
 - OS/Browser: Windows 10
 - Game version: 4.1 branch
 - Other specs: VCS is GitHub Desktop

**Additional context**
Possibly solve in similar way to #227?

**Comment by GTcreyon** [comment]
I'll take a look at this.
