### ISSUE TITLE
Small string of code appears in tutorial sign

### ISSUE THREAD

**Issue by Kokasgui** [GTcreyon/SM63Redux#280]
**Describe the bug**
The text isn't correctly coded in the Tiny Demo's portuguese translation, with inccorect code appearing with the text (it appears `[cor=#f7c55f]bob-ombs[/color]`)

**To Reproduce**
Go to the second screen (the one with the first bob-ombs) and read the first sign

**Expected behavior**
The word "bom-ombs" should appear red

**Screenshots**
![image](https://github.com/GTcreyon/SM63Redux/assets/91392390/e65c09b0-9fac-4368-a49c-47192a79b64a)

**System Information**
 - OS/Browser: Google Chrome
 - Game version: 0.1.6.alpha
 - Other specs:

**Comment by Koopa1018** [comment]
Thanks for the bug report!
