### ISSUE TITLE
Silding

### ISSUE THREAD

**Issue by ChaseyBOIDude** [GTcreyon/SM63Redux#30]
**Describe the feature you'd like**
I would like Mario to be able to slide.

**Do you intend to contribute this yourself? If so, how do you plan on doing it?**
No.

**Additional context**
In order to Slide you would have to hold "Z" and duck.

**Comment by GTcreyon** [comment]
It's unlikely that we would add new movement techniques. We intend to keep Mario's moveset mostly the same as the original.
