### ISSUE TITLE
Improve touch controls

### ISSUE THREAD

**Issue by ChaseyBOI801** [GTcreyon/SM63Redux#32]
**Describe the feature you'd like**
When on Mobile device your able to turn on ui for touch controls but they block up the screen and when playing it it's hard to see what is going on, so I would suggest we make the Buttons smaller or change the sprite entirely, it's just annoying to deal with. 

**Do you intend to contribute this yourself? If so, how do you plan on doing it?**
I know a tiny bit of JavaScript, but I don't know anything about GDscript so You guys will have to implement this feature.

**Comment by GTcreyon** [comment]
This is already in the works, don't worry!

**Comment by GTcreyon** [comment]
Not sure why this wasn't closed before. Pretty sure I finished this sometime last year.
