### ISSUE TITLE
Ad for SM63 Redux

### ISSUE THREAD

**Issue by ChaseyBOI801** [GTcreyon/SM63Redux#33]
**Describe the feature you'd like**
I have editing skills and when checking on your video about the game many comments say they never knew the game existed, so maybe I can create a short AD for the game. I sure you're not going to agree to this but make this a possibility if the time comes.

**Do you intend to contribute this yourself? If so, how do you plan on doing it?**
Yes, I'm editing the entire video.

**Comment by GTcreyon** [comment]
If you'd like to help with the game's development generally, please apply using this form. https://forms.gle/mJyF3iYZMwMhq1xE7
