### ISSUE TITLE
Text not fully visible in feedback menu

### ISSUE THREAD

**Issue by PoketrainerMS** [GTcreyon/SM63Redux#40]
**Describe the bug**
The text in the "report includes" list gets cut off by the bottom of the game window

**To Reproduce**
literally just press F1 and open the feedback menu lmao

**Expected behavior**
I thought I'd be able to read the text of what the report includes, but it gets cut off.

**Screenshots**
![image](https://user-images.githubusercontent.com/83524620/212946734-2e7f6f84-3a70-492f-b78a-9c4fa59344fb.png)

**System Information**
 - OS/Browser: Chrome OS (Chromebook), Chrome
 - Game version: v0.1.5
 - Other specs: honestly idk but i dont think it matters that much when it comes to this (Version 102.0.5005.75 (Official Build) (64-bit) is the version number copied and pasted from my settings)

**Comment by GTcreyon** [comment]
I think this is because of your window's aspect ratio. I should be able to fix this in the menu-fixes branch.

FYI, the missing text is `-Current platform (Windows, Web, Android, etc.)`

**Comment by PoketrainerMS** [comment]
oh yeah if i zoom out a little it shows but the border looks weird, though thats only when i zoom out after opening it
![image](https://user-images.githubusercontent.com/83524620/213210332-1dbee5ef-5a7d-4b14-b808-19c31d151741.png)
yes im on a school chromebook rn rocks are boring lmao
and the "fast" in google drive is where i upload screen recordings of speedruns so i can view them from my home computer

**Comment by GTcreyon** [comment]
> oh yeah if i zoom out a little it shows but the border looks weird, though thats only when i zoom out after opening it ![image](https://user-images.githubusercontent.com/83524620/213210332-1dbee5ef-5a7d-4b14-b808-19c31d151741.png) yes im on a school chromebook rn rocks are boring lmao and the "fast" in google drive is where i upload screen recordings of speedruns so i can view them from my home computer

Ah, yeah, the web version behaves a little differently.
