### ISSUE TITLE
Command "health INF" isn't recognized

### ISSUE THREAD

**Issue by PoketrainerMS** [GTcreyon/SM63Redux#42]
**Describe the bug**
Exactly as the title and "To Reproduce" say.

**To Reproduce**
Press `/`, type `health INF`. It says "`Unknown command 'health'.`"

**Expected behavior**
> If you press `/`, it will open up a command line that you can enter cheats into. Try `fludd all`, `health INF` and `cherry` in particular.

-quoted from #20 
Judging by the name, I assume it's supposed to make it so you cannot take damage.

**Screenshots**
[Screen recording 2023-01-18 10.30.28 AM.webm](https://user-images.githubusercontent.com/83524620/213216261-417b3f4c-8031-45c2-95a6-a3b045bf2d0d.webm)
ignore my bad typing skills 😭 

**System Information**
 - OS/Browser: Chrome OS (Chromebook), Chrome
 - Game version: v0.1.5
 - Other specs: Chromebook Version 102.0.5005.75 (Official Build) (64-bit)

**Comment by GTcreyon** [comment]
Turns out, that command doesn't actually exist at all. I guess I forgot to add it? Either way, I've added it now. `health INF` still doesn't actually work due to how it's set up, but `health 9` should make you invincible in 0.2.0.

Closed by 13e79d69.

**Comment by PoketrainerMS** [comment]
Cool. Thank you!
