### ISSUE TITLE
Proper "EXIT" button in the Pause Menu, to exit to the Title Screen.

### ISSUE THREAD

**Issue by PoketrainerMS** [GTcreyon/SM63Redux#43]
**Describe the feature you'd like**
An easy way to exit to the title screen. Right now, the only way to do this is restarting the entire game.

**Do you intend to contribute this yourself? If so, how do you plan on doing it?**
I don't know too much about coding yet (I want to, this kind of thing is my dream job), so no.

**Additional context**
[What it looks like now, and how annoying it is to refresh every time.](https://user-images.githubusercontent.com/83524620/213223433-0e585786-8a22-4701-91b5-0572ebcec88c.webm)
Just a simple button to return to the title screen in the "Exit" section of the Pause menu would be fine until the Pause menus are fixed.
You could even just rip the image from the original game!

**Comment by PoketrainerMS** [comment]
also sorry for opening so many issues within a short time period, im just doing this while im thinking about it, otherwise i wont remember later 😭

**Comment by GTcreyon** [comment]
> also sorry for opening so many issues within a short time period, im just doing this while im thinking about it, otherwise i wont remember later sob

It's fine! As long as issues are constructive (which this is), it's alright.

This will probably be added sometime after the menu-fixes branch is finished.

**Comment by PoketrainerMS** [comment]
WAIT THERES A COMMAND FOR THIS?????
`title`
I DID THAT AS A JOKE LMAO I DIDNT THINK IT WOULD WORK
though the timer keeps going when you do that
