### ISSUE TITLE
Bob-ombs should flash red when lit

### ISSUE THREAD

**Issue by Koopa1018** [GTcreyon/SM63Redux#53]
**Describe the feature you'd like**
As suggested by Creyon in #45, Bob-ombs should blink red in time with the explosion buildup sound. Would provide stronger visual feedback that the Bob-omb is dangerous now.

**Do you intend to contribute this yourself? If so, how do you plan on doing it?**
Wouldn't mind doing it. There are two approaches I might use:
1. Palette shader. Set the Bob-omb's shell to palette-swap, then strobe the palette between black and red. Light on artist involvement, heavy on programming; may require some custom shader work (depending on how flexible the existing palette shader is).
2. Separate body from feet. Bob-omb is already split into three sprites (fuse, key, body); might as well make a fourth. Body would have handmade levels of redness, from fully black to fully red. Heavy on artist involvement, light on programming; easier to art-direct, but implies stair-step levels of redness rather than smooth blending.

**Comment by GTcreyon** [comment]
I don't think a shader nor handmade sprites is necessary. You could just separate the body and use modulate.r to color it red, using a sine function to animate it.
