### ISSUE TITLE
Spin sound keeps playing when reading signs

### ISSUE THREAD

**Issue by Koopa1018** [GTcreyon/SM63Redux#59]
**Describe the bug**
Interacting with a sign while spinning does not stop the spin sound.

**To Reproduce**
1. Go to any room with a sign (t1r1 or t1r2 recommended)
2. Spin
3. With spin still held down, interact with a sign

**Expected behavior**
Spin sound never plays when the player is not spinning.

**Screenshots**
None, audio bug

**System Information**
 - OS/Browser: Windows 10
 - Game version: 0.2.0 alpha
 - Other specs:

**Comment by GTcreyon** [comment]
Correction, game version is 0.2.0 alpha.

**Comment by Koopa1018** [comment]
New discovery: cannot reproduce with toads, only with signs.
