### ISSUE TITLE
Question: What does /c do?

### ISSUE THREAD

**Issue by PoketrainerMS** [GTcreyon/SM63Redux#61]
I was looking through the code for the console commands, and I noticed `/c` is a command, and it toggles some kind of "classic mode", though when I tried it, nothing seemed to change.
What does/will it do?

###### also how do i add labels to an issue?

**Comment by ChaseyBOI801** [comment]
I think it changes the sprites from the new ones to the ones from the original

**Comment by PoketrainerMS** [comment]
> I think it changes the sprites from the new ones to the ones from the original

That's what i thought, but no.

**Comment by GTcreyon** [comment]
It does nothing at all.

It was originally planned to change some things about the physics to make it more accurate to the original, but that idea was scrapped.

**Comment by PoketrainerMS** [comment]
Interesting.

**Comment by ChaseyBOI801** [comment]
Maybe we could bring back /c? sounds like it would have been cool.

**Comment by GTcreyon** [comment]
> I know Wario is Going to be in the Game so maybe for the `/c` it changes his sprite to the Wario Sprite from Wario Land 4? idk just an idea.

We will not be adding sprite swaps of any kind. Too much effort for something that should be relegated to a texture mod.

**Comment by ChaseyBOI801** [comment]
> > I know Wario is Going to be in the Game so maybe for the `/c` it changes his sprite to the Wario Sprite from Wario Land 4? idk just an idea.
> 
> We will not be adding sprite swaps of any kind. Too much effort for something that should be relegated to a texture mod.

Maybe We could add it after the game releases and make it part of a update.

**Comment by GTcreyon** [comment]
> Maybe We could add it after the game releases and make it part of a update.

No. We would be focusing on other things. Again, it would have to be a mod made by someone else.

Locking this thread now, since it has become off-topic.
