### ISSUE TITLE
Question: How do you get access to 0.2.0v ?

### ISSUE THREAD

**Issue by ChaseyBOI801** [GTcreyon/SM63Redux#62]
In The Trailer for SM63 Redux on your channel @GTcreyon You have access to the Level Designer, and on the title screen in the bottom left corner it says "0.2.0v" so I was wondering where you could find it so I can test the game for more bugs.

**Comment by Koopa1018** [comment]
Download the GitHub repo's code, then open it in Godot.

(Or, if you know how to clone a repo, do that so you can update easier.)

**Comment by GTcreyon** [comment]
The 0.2.0 version is an unfinished development version. So far, there's no executable for it, just source code.
If you download all the code from the Code section of the repository, you can open it in the [Godot engine](https://godotengine.org/download/windows/) and play it from there, but it's very buggy and unfinished.
