### ISSUE TITLE
Can't enter slash character in the console

### ISSUE THREAD

**Issue by GTcreyon** [GTcreyon/SM63Redux#72]
**Describe the bug**
Pressing `/` while the console is shown will close the console. This means that file paths cannot be entered, rendering the `scene` command useless.

**Expected behavior**
A `/` character should be written. Perhaps the ESC key could be used to close the console instead.

**Comment by RandomCatDude** [comment]
i personally think the tilde (`~`) key would make more sense as the main open/close bind, but `/` could remain as a bind to open it, and ya `esc` could be a secondary way to close it

**Comment by GTcreyon** [comment]
> i personally think the tilde (`~`) key would make more sense as the main open/close bind

I object to this, because the position of that key varies significantly on different keyboard layouts. For me, I have a `~/#` key, and it's next to the Enter key. Others have it in the top left of the keyboard, apparently.

**Comment by RandomCatDude** [comment]
yeah fair
i suppose the most ideal way is to have a bind option for the console toggle
