### ISSUE TITLE
While in-game, settings menu UI elements scale incorrectly on high resolutions

### ISSUE THREAD

**Issue by RandomCatDude** [GTcreyon/SM63Redux#8]
**Describe the bug**
While in a level, If the game window is large enough to the point that the UI elements are scaled up to compensate, most elements in the settings menu appear oversized, becoming difficult to use. Only exceptions are the "Show Timer" text, and the language selection.

**To Reproduce**
1. Enter any level
2. Press P to pause, and go to the Settings menu
3. Increase the size of the window, go fullscreen if needed
4. Observe the options becoming oversized.

**Expected behavior**
UI elements in the settings menu while in-game, should work as they do in the main menu, remaining reasonably sized.

**Screenshots**
![image](https://user-images.githubusercontent.com/71602778/193346744-97ad92d2-fa8c-4a52-b741-e19001e318c4.png)
For comparison -- in the main menu, UI scales appropriately:
![image](https://user-images.githubusercontent.com/71602778/193348217-012ed119-8028-4daa-8231-8f3943eef776.png)

**System Information**
 - OS/Browser: Linux/Windows (any platform with a resizable window and high-res displays)
 - Game version: v0.2.0.alpha

**Comment by GTcreyon** [comment]
I'll most likely fix this while adding the touch control customization.

**Comment by GTcreyon** [comment]
> I'll most likely fix this while adding the touch control customization.

I might not, actually. This probably needs to be dealt with separately, in a full menuing rewrite.
Being able to define menus via text strings might be nice - building them in the editor is currently very annoying and unstable.
